### PR TITLE
added healthy items to groceries

### PR DESCRIPTION
**Pull request by Dangoz**
Resolves: #1

added HEALTHY items to groceries, please check🍰 @iflinda

### CODE REVIEW

**Comment by iflinda** [comment]
👍 Good job, but could you also add kombucha?

**Review by iflinda — CHANGES_REQUESTED** [review]
@Dangoz Could you double check the item list again. I wanted to add bottled water and green juice. 👍

**Comment by Dangoz** [comment]
> @Dangoz Could you double check the item list again. I wanted to add bottled water and green juice. 👍

updated groceries with the correct items.

**Review by iflinda — APPROVED** [review]
👍 Looks good. I'll go ahead and merge.

**Pull request merged**
